
language: node_js
node_js:
  - "6"
  - "8"
services:
  - postgresql
cache:
  directories:
  - node_modules
git:
  depth: 1
before_script:
  - psql -c 'create database nexa;' -U postgres
script:
  - npm run coverage
